user_token: OTY3NmVjYWYtZTJhNC00NzNhLTgwM2YtZGY3OTBkYTM3YWFhXzQ1Mzk=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 0.0.0.0
  port: 5432
  user: kts_user
  password: kts_pass
  database: kts
bot:
  token: vk1.a.JJ5gbDvEDwMrGx54Zi01dMRWJgxD8dzXDtSnsA2y6_cbBH7pq5DOlt4qljywyrqczyTzybXZ2rKkOF3f0XW65xYPQ2B_tYPRe3Bwb_OIQuFG60TB6CD8_Ln9FqcsZmo52rUcMNes_35ft-WlQrCv0rFpFj9HXQhuTszciKdmI1mXy00_pVqbzW183G3m9hUpPah9PurAiO2GzyGHmdgpTQ
  group_id: 218928416


